# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\ESC\ASC-ODE\ASC-ODE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\ESC\ASC-ODE\ASC-ODE\ASC-bla

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\ESC\ASC-ODE\ASC-ODE\ASC-bla\CMakeFiles C:\ESC\ASC-ODE\ASC-ODE\ASC-bla\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\ESC\ASC-ODE\ASC-ODE\ASC-bla\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_ode

# Build rule for target.
test_ode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_ode
.PHONY : test_ode

# fast build rule for target.
test_ode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_ode.dir\build.make CMakeFiles/test_ode.dir/build
.PHONY : test_ode/fast

#=============================================================================
# Target rules for targets named test_newmark

# Build rule for target.
test_newmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_newmark
.PHONY : test_newmark

# fast build rule for target.
test_newmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_newmark.dir\build.make CMakeFiles/test_newmark.dir/build
.PHONY : test_newmark/fast

#=============================================================================
# Target rules for targets named test_alpha

# Build rule for target.
test_alpha: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_alpha
.PHONY : test_alpha

# fast build rule for target.
test_alpha/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_alpha.dir\build.make CMakeFiles/test_alpha.dir/build
.PHONY : test_alpha/fast

demos/test_alpha.obj: demos/test_alpha.cc.obj
.PHONY : demos/test_alpha.obj

# target to build an object file
demos/test_alpha.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_alpha.dir\build.make CMakeFiles/test_alpha.dir/demos/test_alpha.cc.obj
.PHONY : demos/test_alpha.cc.obj

demos/test_alpha.i: demos/test_alpha.cc.i
.PHONY : demos/test_alpha.i

# target to preprocess a source file
demos/test_alpha.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_alpha.dir\build.make CMakeFiles/test_alpha.dir/demos/test_alpha.cc.i
.PHONY : demos/test_alpha.cc.i

demos/test_alpha.s: demos/test_alpha.cc.s
.PHONY : demos/test_alpha.s

# target to generate assembly for a file
demos/test_alpha.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_alpha.dir\build.make CMakeFiles/test_alpha.dir/demos/test_alpha.cc.s
.PHONY : demos/test_alpha.cc.s

demos/test_newmark.obj: demos/test_newmark.cc.obj
.PHONY : demos/test_newmark.obj

# target to build an object file
demos/test_newmark.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_newmark.dir\build.make CMakeFiles/test_newmark.dir/demos/test_newmark.cc.obj
.PHONY : demos/test_newmark.cc.obj

demos/test_newmark.i: demos/test_newmark.cc.i
.PHONY : demos/test_newmark.i

# target to preprocess a source file
demos/test_newmark.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_newmark.dir\build.make CMakeFiles/test_newmark.dir/demos/test_newmark.cc.i
.PHONY : demos/test_newmark.cc.i

demos/test_newmark.s: demos/test_newmark.cc.s
.PHONY : demos/test_newmark.s

# target to generate assembly for a file
demos/test_newmark.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_newmark.dir\build.make CMakeFiles/test_newmark.dir/demos/test_newmark.cc.s
.PHONY : demos/test_newmark.cc.s

demos/test_ode.obj: demos/test_ode.cc.obj
.PHONY : demos/test_ode.obj

# target to build an object file
demos/test_ode.cc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_ode.dir\build.make CMakeFiles/test_ode.dir/demos/test_ode.cc.obj
.PHONY : demos/test_ode.cc.obj

demos/test_ode.i: demos/test_ode.cc.i
.PHONY : demos/test_ode.i

# target to preprocess a source file
demos/test_ode.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_ode.dir\build.make CMakeFiles/test_ode.dir/demos/test_ode.cc.i
.PHONY : demos/test_ode.cc.i

demos/test_ode.s: demos/test_ode.cc.s
.PHONY : demos/test_ode.s

# target to generate assembly for a file
demos/test_ode.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_ode.dir\build.make CMakeFiles/test_ode.dir/demos/test_ode.cc.s
.PHONY : demos/test_ode.cc.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... test_alpha
	@echo ... test_newmark
	@echo ... test_ode
	@echo ... demos/test_alpha.obj
	@echo ... demos/test_alpha.i
	@echo ... demos/test_alpha.s
	@echo ... demos/test_newmark.obj
	@echo ... demos/test_newmark.i
	@echo ... demos/test_newmark.s
	@echo ... demos/test_ode.obj
	@echo ... demos/test_ode.i
	@echo ... demos/test_ode.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

