
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx86/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ wersja kompilatora optymalizującego 19.37.32824 dla x64
      Copyright (C) Microsoft Corporation. Wszystkie prawa zastrzeżone.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.37.32824.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/3.27.7/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Uwaga: w tym pliku:  C:\\ESC\\ASC-bla\\_skbuild\\win-amd64-3.8\\cmake-build\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Uwaga: w tym pliku:  "
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx86/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ wersja kompilatora optymalizującego 19.37.32824 dla x64
      Copyright (C) Microsoft Corporation. Wszystkie prawa zastrzeżone.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.37.32824.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Uwaga: w tym pliku:  C:\\ESC\\ASC-bla\\_skbuild\\win-amd64-3.8\\cmake-build\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Uwaga: w tym pliku:  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeScratch/TryCompile-eeaguj"
      binary: "C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeScratch/TryCompile-eeaguj"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/skbuild/resources/cmake"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeScratch/TryCompile-eeaguj'
        
        Run Build Command(s): C:/PROGRA~1/MICROS~4/2022/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe -v cmTC_3de78
        [1/2] C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx86\\x64\\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_3de78.dir\\CMakeCCompilerABI.c.obj /FdCMakeFiles\\cmTC_3de78.dir\\ /FS -c C:\\Users\\Micha┼é\\AppData\\Local\\Temp\\pip-build-env-264okop3\\overlay\\Lib\\site-packages\\cmake\\data\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c
        [2/2] cmd.exe /C "cd . && C:\\Users\\Micha┼é\\AppData\\Local\\Temp\\pip-build-env-264okop3\\overlay\\Lib\\site-packages\\cmake\\data\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_3de78.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x86\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x86\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx86\\x64\\link.exe /nologo CMakeFiles\\cmTC_3de78.dir\\CMakeCCompilerABI.c.obj  /out:cmTC_3de78.exe /implib:cmTC_3de78.lib /pdb:cmTC_3de78.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeScratch/TryCompile-n8389r"
      binary: "C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeScratch/TryCompile-n8389r"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/skbuild/resources/cmake"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeScratch/TryCompile-n8389r'
        
        Run Build Command(s): C:/PROGRA~1/MICROS~4/2022/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe -v cmTC_98c01
        [1/2] C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx86\\x64\\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /EHsc  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_98c01.dir\\CMakeCXXCompilerABI.cpp.obj /FdCMakeFiles\\cmTC_98c01.dir\\ /FS -c C:\\Users\\Micha┼é\\AppData\\Local\\Temp\\pip-build-env-264okop3\\overlay\\Lib\\site-packages\\cmake\\data\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp
        [2/2] cmd.exe /C "cd . && C:\\Users\\Micha┼é\\AppData\\Local\\Temp\\pip-build-env-264okop3\\overlay\\Lib\\site-packages\\cmake\\data\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_98c01.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x86\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x86\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx86\\x64\\link.exe /nologo CMakeFiles\\cmTC_98c01.dir\\CMakeCXXCompilerABI.cpp.obj  /out:cmTC_98c01.exe /implib:cmTC_98c01.lib /pdb:cmTC_98c01.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CheckCXXCompilerFlag.cmake:34 (cmake_check_compiler_flag)"
      - "C:/Python38/share/cmake/pybind11/pybind11Common.cmake:276 (check_cxx_compiler_flag)"
      - "C:/Python38/share/cmake/pybind11/pybind11Common.cmake:340 (_pybind11_return_if_cxx_and_linker_flags_work)"
      - "C:/Python38/share/cmake/pybind11/pybind11Common.cmake:385 (_pybind11_generate_lto)"
      - "C:/Python38/share/cmake/pybind11/pybind11Config.cmake:250 (include)"
      - "CMakeLists.txt:16 (find_package)"
    checks:
      - "Performing Test HAS_MSVC_GL_LTCG"
    directories:
      source: "C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeScratch/TryCompile-9hrm1a"
      binary: "C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeScratch/TryCompile-9hrm1a"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "C:/Users/Micha\u0142/AppData/Local/Temp/pip-build-env-264okop3/overlay/Lib/site-packages/skbuild/resources/cmake"
    buildResult:
      variable: "HAS_MSVC_GL_LTCG"
      cached: true
      stdout: |
        Change Dir: 'C:/ESC/ASC-bla/_skbuild/win-amd64-3.8/cmake-build/CMakeFiles/CMakeScratch/TryCompile-9hrm1a'
        
        Run Build Command(s): C:/PROGRA~1/MICROS~4/2022/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe -v cmTC_cfc9f
        [1/2] C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx86\\x64\\cl.exe  /nologo /TP -DHAS_MSVC_GL_LTCG  /DWIN32 /D_WINDOWS /EHsc  /Zi /Ob0 /Od /RTC1 -std:c++17 -MDd   /GL /showIncludes /FoCMakeFiles\\cmTC_cfc9f.dir\\src.cxx.obj /FdCMakeFiles\\cmTC_cfc9f.dir\\ /FS -c C:\\ESC\\ASC-bla\\_skbuild\\win-amd64-3.8\\cmake-build\\CMakeFiles\\CMakeScratch\\TryCompile-9hrm1a\\src.cxx
        [2/2] cmd.exe /C "cd . && C:\\Users\\Micha┼é\\AppData\\Local\\Temp\\pip-build-env-264okop3\\overlay\\Lib\\site-packages\\cmake\\data\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_cfc9f.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x86\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x86\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~4\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx86\\x64\\link.exe /nologo CMakeFiles\\cmTC_cfc9f.dir\\src.cxx.obj  /out:cmTC_cfc9f.exe /implib:cmTC_cfc9f.lib /pdb:cmTC_cfc9f.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  -LTCG  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
...
